import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "미니어쳐 팀",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
